<!-- Badges: -->

<!-- Title: -->
<div align="center">
  <h1><b> Implementations </b></h1>
  <h2> Quantum Circuit Theory and Implementations </h2>
</div>
<br>

<b>Author:</b> <a target="_blank" href="https://github.com/camponogaraviera">Lucas Camponogara Viera</a>

<div align='center'>
<table class="tfo-notebook-buttons" align="head">
  <td>
    <a target="_blank" href="https://github.com/QuCAI-Lab/quantum-circuit-theory"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" /></a>
  </td>
</table>
</div>

---
The reader may also resort to the [IBM's Summary of Quantum Operations](https://qiskit.org/documentation/tutorials/circuits/3_summary_of_quantum_operations.html) and the [Operations Glossary](https://quantum-computing.ibm.com/composer/docs/iqx/operations_glossary) for Qiskit implementations of the same.

---

In [2]:
%run init.ipynb

Author: Lucas Camponogara Viera

Github username: camponogaraviera

Website: https://qucai-lab.github.io/

Last updated: 2023-05-20

Python implementation: CPython
Python version       : 3.11.2
IPython version      : 8.13.2

Compiler    : GCC 11.2.0
OS          : Linux
Release     : 5.19.0-41-generic
Machine     : x86_64
Processor   : x86_64
CPU cores   : 4
Architecture: 64bit

Git repo: https://github.com/QuCAI-Lab/quantum-circuit-theory.git

Git branch: dev

watermark : 2.3.1
sympy     : 1.11.1
pennylane : 0.28.0
IPython   : 8.13.2
scipy     : 1.9.3
numpy     : 1.23.5
pylatexenc: 2.10
matplotlib: 3.6.2

Watermark: 2.3.1

{'commit_hash': '2c4c28a3a',
 'commit_source': 'installation',
 'default_encoding': 'utf-8',
 'ipython_path': '/home/lucas/anaconda3/envs/qct/lib/python3.11/site-packages/IPython',
 'ipython_version': '8.13.2',
 'os_name': 'posix',
 'platform': 'Linux-5.19.0-41-generic-x86_64-with-glibc2.35',
 'sys_executable': '/home/lucas/anaconda3/envs/qct/bin/python',
 'sys_platf

# Table of Contents

- NumPy and Sympy implementations of:
  - Basis states.
  - Projector operators.
  - Single-qubit gates.
  - Two-qubit gates.
  - Eigenvalues and eigenvectors.

# Basis states

In [3]:
'''Eigenstates of the Pauli-Z gate (Z-basis):'''
zero=np.array([[1,0]]) # 2D row-like (bra vector) numpy array representing the classical state <0|.
one=np.array([[0,1]])  # 2D row-like (bra vector) numpy array representing the classical state <1|.

'''Eigenstates of the Pauli-X gate (X-basis):'''
plus=1/(np.sqrt(2))*(zero+one)  # 2D row-like numpy array (bra vector) representing the superposition state <+| = 1/[sqrt(2)](<0| + <1|).
minus=1/(np.sqrt(2))*(zero-one) # 2D row-like numpy array (bra vector) representing the superposition state <-| = 1/[sqrt(2)](<0| - <1|).

'''Eigenstates of the Pauli-Y gate (Y-basis):'''
oplus=1/(np.sqrt(2))*(zero+1j*one)  # 2D row-like numpy array (bra vector) representing the superposition state <⊕| = 1/[sqrt(2)](<0| + i<1|).
ominus=1/(np.sqrt(2))*(zero-1j*one) # 2D row-like numpy array (bra vector) representing the superposition state <⊖| = 1/[sqrt(2)](<0| - i<1|).

zero.shape, one.shape, plus.shape, minus.shape, oplus.shape, ominus.shape

((1, 2), (1, 2), (1, 2), (1, 2), (1, 2), (1, 2))

In [4]:
'''
# Row vector:
np.array([0, 1]).reshape(1, 2)

# Column vector:
np.array([0, 1]).reshape(2, 1) 
'''

'\n# Row vector:\nnp.array([0, 1]).reshape(1, 2)\n\n# Column vector:\nnp.array([0, 1]).reshape(2, 1) \n'

In [24]:
zero_zero = np.kron(zero.T,zero.T)
zero_one = np.kron(zero.T,one.T)
one_zero = np.kron(one.T,zero.T)
one_one = np.kron(one.T,one.T)

zero_zero, zero_one, one_zero, one_one

(array([[1],
        [0],
        [0],
        [0]]),
 array([[0],
        [1],
        [0],
        [0]]),
 array([[0],
        [0],
        [1],
        [0]]),
 array([[0],
        [0],
        [0],
        [1]]))

# Projector operators

In [5]:
'''Projector operators of the ZZ gate:'''
outzero = zero.T@zero # Matrix of the outer product |0><0|.
outone = one.T@one # Matrix of the outer product |1><1|.

#zeros=np.outer(np.kron(zero,zero),np.kron(zero,zero)) # Matrix of the outer product |00><00|.
#ones=np.outer(np.kron(one,one),np.kron(one,one))      # Matrix of the outer product |11><11|.
#zerone=np.outer(np.kron(zero,one),np.kron(zero,one))  # Matrix of the outer product |01><01|.
#onezero=np.outer(np.kron(one,zero),np.kron(one,zero)) # Matrix of the outer product |10><10|.
zeros=np.kron(zero.T,zero.T)@np.kron(zero,zero) # Matrix of the outer product |00><00|.
ones=np.kron(one.T,one.T)@np.kron(one,one)      # Matrix of the outer product |11><11|.
zerone=np.kron(zero.T,one.T)@np.kron(zero,one)  # Matrix of the outer product |01><01|.
onezero=np.kron(one.T,zero.T)@np.kron(one,zero) # Matrix of the outer product |10><10|.

# Single-qubit gates

## Pauli gates

In [6]:
'''Matrix of the identity gate:'''
sigma0 = np.identity(2) 

'''Matrix of the Pauli-X gate that performs a Pi radian rotation around the x-axis:'''
#sigma1 = (plus.T@plus)-(minus.T@minus) # |+><+|-|-><-|
sigma1 = np.array([[0,1],[1,0]], dtype=(np.float32)) 

'''Matrix of the Pauli-Y gate = iXZ that performs a Pi radian rotation around the y-axis:'''
#sigma2 = (oplus.T@oplus)-(ominus.T@ominus) # |⊕><⊕|-|⊖><⊖|
sigma2 = np.array([[0,-1j],[1j,0]], dtype=(np.complex64)) 

'''Matrix of the Pauli-Z gate = P(pi) that performs a Pi radian rotation around the z-axis:'''
#sigma3 = (zero.T@zero)-(one.T@one) # |0><0|-|1><1|
sigma3 = np.array([[1,0],[0,-1]], dtype=(np.float32)) 

In [7]:
sigma1

array([[0., 1.],
       [1., 0.]], dtype=float32)

In [8]:
sigma2

array([[ 0.+0.j, -0.-1.j],
       [ 0.+1.j,  0.+0.j]], dtype=complex64)

In [9]:
sigma3

array([[ 1.,  0.],
       [ 0., -1.]], dtype=float32)

## Hadamard gate 

In [10]:
# Matrix of the Hadamard gate that performs a Pi radian rotation around an axis between the x and z axes.

had = (1/np.sqrt(2))*np.array([[1,1],[1,-1]]) 

## Phase gate $S$

In [11]:
# Matrix of the Phase gate S = P(pi/2) = square-root of Pauli-Z that performs a rotation of pi/2 radians around the z-axis.

phase_s = np.array([[1,0],[0,1j]]) 
phase_s

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j]])

## Phase gate $T$ a.k.a $\pi/8$ gate

In [12]:
# Matrix of the Phase gate T = fourth-root of Pauli-Z that performs a rotation of pi/4 radians around the z-axis.

phase_t = np.array([[1,0],[0,np.exp(1j*np.pi/4)]]) 
phase_t

array([[1.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.70710678+0.70710678j]])

## $R_{\hat{n}}(\theta)$ single-qubit standard rotation gate

In [13]:
def Rn(nx: int, ny: int, nz: int, theta: float) -> np.ndarray:
  '''
  Function to compute the Rn(theta) gate that performs a rotation by theta radian around an arbitrary axis of the Bloch sphere.

  Args:
    - nx (int): scalar value (0 or 1).
    - ny (int): scalar value (0 or 1).
    - nz (int): scalar value (0 or 1).
    - theta (float): angle of rotation in radians.
  
  Returns:
    - Rn (numpy.ndarray): the corresponding single-qubit standard rotation gate performing a rotation around an arbitrary axis.
  '''
  unit_vector = nx*sigma1 + ny*sigma2 + nz*sigma3
  Rn = expm(-1j*theta/2*unit_vector)
  return Rn

In [12]:
Rx = Rn(1,0,0,np.pi/2) # Rotation by pi/2 radian around the x-axis.
Rx

array([[0.70710677+0.j        , 0.        -0.70710677j],
       [0.        -0.70710677j, 0.70710677+0.j        ]], dtype=complex64)

In [13]:
Ry = Rn(0,1,0,np.pi/2) # Rotation by pi/2 radian around the x-axis.
Ry

array([[ 0.70710677+0.j, -0.70710677-0.j],
       [ 0.70710677+0.j,  0.70710677+0.j]], dtype=complex64)

In [14]:
Rz = Rn(0,0,1,np.pi/2) # Rotation by pi/2 radian around the x-axis.
Rz

array([[0.70710677-0.70710677j, 0.        +0.j        ],
       [0.        +0.j        , 0.70710677+0.70710677j]], dtype=complex64)

## $R_x (\theta)$ gate

In [15]:
def RX(theta: float) -> np.ndarray:
  '''
  Function to compute the Special Orthogonal matrix (SO(2) group) of the RX(theta) gate that performs a rotation by theta radian around the x-axis.

  Args:
    - theta (float): angle of rotation in radians.
  
  Returns:
    - RX (numpy.ndarray): the corresponding single-qubit gate performing a rotation around the x-axis.
  '''
  RX = np.array([
  [np.cos(theta/2),-1j*np.sin(theta/2)],
  [-1j*np.sin(theta/2), np.cos(theta/2)]
  ])
  return RX

In [16]:
rx_pi2=RX(np.pi/2) # Rotation by pi/2 radian around the x-axis.
rx_pi2

array([[0.70710678+0.j        , 0.        -0.70710678j],
       [0.        -0.70710678j, 0.70710678+0.j        ]])

In [17]:
rx_mpi2=RX(-np.pi/2) # Rotation by -pi/2 radian around the x-axis.
rx_mpi2

array([[0.70710678+0.j        , 0.        +0.70710678j],
       [0.        +0.70710678j, 0.70710678+0.j        ]])

In [18]:
np.linalg.det(RX(-np.pi/2))

(1+0j)

## $R_y (\theta)$ gate

In [19]:
def RY(theta: float) -> np.ndarray:
  '''
  Function to compute the Special Orthogonal matrix (SO(2) group) of the RY(theta) gate that performs a rotation by theta radian around the y-axis.

  Args:
    - theta (float): angle of rotation in radians.
  
  Returns:
    - RY (numpy.ndarray): the corresponding single-qubit gate performing a rotation around the y-axis.
  '''
  RY = np.array([
    [np.cos(theta/2),-np.sin(theta/2)],
    [np.sin(theta/2), np.cos(theta/2)]
  ])
  return RY

In [20]:
ry_pi2=RY(np.pi/2) # Rotation by pi/2 radian around the y-axis.
ry_pi2

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [21]:
ry_mpi2=RY(-np.pi/2) # Rotation by -pi/2 radian around the y-axis.
ry_mpi2

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

## $R_z (\theta)$ gate

In [22]:
def RZ(theta: float) -> np.ndarray:
  '''
  Function to compute the Special Orthogonal matrix (SO(2) group) of the RZ(theta) gate that performs a rotation by theta radian around the z-axis.

  Args:
    - theta (float): angle of rotation in radians.
  
  Returns:
    - RZ (numpy.ndarray): the corresponding single-qubit gate performing a rotation around the z-axis.
  '''
  RZ = np.array([
  [np.exp(-1j*theta/2), 0],
  [0, np.exp(1j*theta/2)]
  ])
  return RZ

In [23]:
RZ(np.pi/2) # Rotation by pi/2 radian around the z-axis.

array([[0.70710678-0.70710678j, 0.        +0.j        ],
       [0.        +0.j        , 0.70710678+0.70710678j]])

In [24]:
RZ(-np.pi/2) # Rotation by -pi/2 radian around the z-axis.

array([[0.70710678+0.70710678j, 0.        +0.j        ],
       [0.        +0.j        , 0.70710678-0.70710678j]])

# Two-qubit gates

## CNOT

$$CX^{q_0q_1} = \mathbb{I} \otimes |0\rangle\langle 0| + X \otimes |1 \rangle \langle 1|.$$

In [18]:
cnot_01 = np.kron(np.eye(2), outzero) + np.kron(sigma1, outone)
cnot_01

array([[1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.]])

$$CX^{q_1q_0}=|0\rangle\langle 0|\otimes \mathbb{I} +|1\rangle\langle 1|\otimes X.$$

In [20]:
cnot_10 = np.kron(outzero, np.eye(2)) + np.kron(outone, sigma1)
cnot_10

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]])

## $XX$ gate:

$$XX \equiv X\otimes X :$$

In [25]:
XX = np.kron(sigma1,sigma1) # Matrix of the XX gate.
XX

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]], dtype=float32)

$$XX \equiv X\otimes X = (|+\rangle\langle +|-|-\rangle\langle -|)\otimes(|+\rangle\langle +|-|-\rangle\langle -|):$$

In [26]:
np.kron((plus.T@plus)-(minus.T@minus), (plus.T@plus)-(minus.T@minus))

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

$$XX \equiv X\otimes X = (|+\rangle\langle +|) \otimes (|+\rangle\langle +|) - (|+\rangle\langle +|) \otimes (|-\rangle\langle -|) - (|-\rangle\langle -|)\otimes (|+\rangle\langle +|) + (|-\rangle\langle -|) \otimes (|-\rangle\langle -|):$$

In [27]:
np.kron((plus.T@plus),(plus.T@plus))-np.kron((plus.T@plus),(minus.T@minus))-np.kron((minus.T@minus),(plus.T@plus))+np.kron((minus.T@minus),(minus.T@minus))

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

$$XX \equiv X\otimes X =(|++\rangle\langle ++|)+(|--\rangle\langle --|)-(|+-\rangle\langle +-|)-(|-+\rangle\langle -+|)$$

In [28]:
(np.kron(plus.T,plus.T)@np.kron(plus,plus))+(np.kron(minus.T,minus.T)@np.kron(minus,minus))-(np.kron(plus.T,minus.T)@np.kron(plus,minus))-(np.kron(minus.T,plus.T)@np.kron(minus,plus))

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

## $YY$ gate:

$$YY \equiv Y\otimes Y :$$

In [29]:
YY = np.kron(sigma2,sigma2) # Matrix of the YY gate.
YY

array([[ 0.+0.j,  0.-0.j,  0.-0.j, -1.+0.j],
       [ 0.+0.j,  0.+0.j,  1.-0.j,  0.-0.j],
       [ 0.+0.j,  1.-0.j,  0.+0.j,  0.-0.j],
       [-1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j]], dtype=complex64)

# Eigenvalues and eigenvectors

## Verifying the eigenvalues and eigenvectors of the $Z$ and $ZZ$ operators with NumPy:

In [30]:
'''Eigenvalues and Eigenvectors of the Z gate.'''

np.linalg.eig(sigma3) # Eigenvalues: +1, -1 | Eigenvectors: |0⟩, |1⟩.

(array([ 1., -1.], dtype=float32),
 array([[1., 0.],
        [0., 1.]], dtype=float32))

In [31]:
'''Eigenvalues and Eigenvectors of ZZ.'''

ZZ = np.kron(sigma3,sigma3) # Z⊗Z.
np.linalg.eig(ZZ) # Eigenvalues: +1, -1, -1, +1 | Eigenvectors: |00⟩, |01⟩, |10⟩, |11⟩.

(array([ 1., -1., -1.,  1.], dtype=float32),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]], dtype=float32))

## Verifying the eigenvalues and eigenvectors of the $X$ and $XX$ operators with NumPy:

In [32]:
'''Eigenvalues and Eigenvectors of X.'''

#Note: the eigenvalues of the printed numpy.ndarray are not necessarily ordered.

np.linalg.eig(sigma1) # Eigenvalues: +1, -1 | Eigenvectors: |+⟩, |-⟩.

(array([ 1., -1.], dtype=float32),
 array([[ 0.70710677, -0.70710677],
        [ 0.70710677,  0.70710677]], dtype=float32))

In [33]:
'''Eigenvalues and Eigenvectors of XX.'''

np.linalg.eig(XX) # Eigenvalues: +1, -1, +1, -1.

(array([ 1., -1.,  1., -1.], dtype=float32),
 array([[ 0.70710677,  0.70710677,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.70710677, -0.70710677],
        [ 0.        ,  0.        ,  0.70710677,  0.70710677],
        [ 0.70710677, -0.70710677,  0.        ,  0.        ]],
       dtype=float32))

# Determinant 

- Verifying the determinant of the Special Orthogonal matrix $R_x$:

In [34]:
theta = sym.symbols('theta')
RX=sym.Matrix([[sym.cos(theta/2),-1j*sym.sin(theta/2)], [-1j*sym.sin(theta/2),sym.cos(theta/2)]])
RX

Matrix([
[       cos(theta/2), -1.0*I*sin(theta/2)],
[-1.0*I*sin(theta/2),        cos(theta/2)]])

In [35]:
M = sym.Matrix(RX)
M.det().simplify()

1.00000000000000

- Verifying the determinant of the Special Orthogonal matrix $R_y$:

In [36]:
theta = sym.symbols('theta')
RY=sym.Matrix([[sym.cos(theta/2),-sym.sin(theta/2)], [sym.sin(theta/2),sym.cos(theta/2)]])
RY

Matrix([
[cos(theta/2), -sin(theta/2)],
[sin(theta/2),  cos(theta/2)]])

In [37]:
M = sym.Matrix(RY)
M.det().simplify()

1

- Verifying the determinant of the Special Orthogonal matrix $R_z$:

In [38]:
theta = sym.symbols('theta')
RZ=sym.Matrix([[sym.exp(-1j*theta/2),0], [0,sym.exp(1j*theta/2)]])
RZ

Matrix([
[exp(-0.5*I*theta),                0],
[                0, exp(0.5*I*theta)]])

In [39]:
M = sym.Matrix(RZ)
M.det()

1